version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: next
  ignore:
  - dependency-name: nix
    versions:
    - 0.19.1
