language: rust
rust:
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy
script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
matrix:
  allow_failures:
    - rust: nightly
